#
# Makefile for test module.
#

obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_config_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_supported_ic.o
