#
# Makefile for test module.
#

obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_main.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_global.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FT8716) += focaltech_ic_table.o
